[project]
name = "steam-watch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2-cli>=0.8.2",
    "scrapy>=2.13.3",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
