name: Test Steam Watch

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test.yaml"
      - "steam_watch/**"
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"

permissions:
  contents: read

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python
        run: uv python install
      - name: Run linters
        run: |
          uv run black --check --diff steam_watch tests
          uv run isort --check-only steam_watch tests
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python
        run: uv python install
      - name: Run unit tests
        run: |
          uv run pytest tests
          uv run pytest --cov=steam_watch tests | tee coverage.log
          cat coverage.log >> $GITHUB_STEP_SUMMARY
  security-scanner:
    name: Security Scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python
        run: uv python install
      - name: Run Bandit
        run: |
          uv run bandit -r src/schedule_parser/ steam_watch/
  functional-test:
    name: Functional Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Set up Python
        run: uv python install
      - name: Run Scrapy spider
        run: |
          uv run scrapy crawl steam_trains -a station_code=${{ secrets.STATION_CODE }} -o steam_trains.json
  zizmor:
    name: GitHub Actions Static Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read # only needed for private repos
      actions: read # only needed for private repos
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@e673c3917a1aef3c65c972347ed84ccd013ecda4 # v0.2.0
